// The world's recognized sovereign countries, each mapped to its ISO 3166-1
// alpha-2 code. The code doubles as the flag filename in /public/flags/<code>.svg.
// Kept flat and pure so it can be searched, sorted, and unit-tested with no DOM.

export type Region =
  | "Africa"
  | "Americas"
  | "Asia"
  | "Europe"
  | "Oceania";

export interface Country {
  /** ISO 3166-1 alpha-2, lowercase. Matches /public/flags/<code>.svg */
  code: string;
  name: string;
  region: Region;
}

// 194 recognized countries (193 UN member states + Vatican City).
export const COUNTRIES: Country[] = [
  { code: "af", name: "Afghanistan", region: "Asia" },
  { code: "al", name: "Albania", region: "Europe" },
  { code: "dz", name: "Algeria", region: "Africa" },
  { code: "ad", name: "Andorra", region: "Europe" },
  { code: "ao", name: "Angola", region: "Africa" },
  { code: "ag", name: "Antigua and Barbuda", region: "Americas" },
  { code: "ar", name: "Argentina", region: "Americas" },
  { code: "am", name: "Armenia", region: "Asia" },
  { code: "au", name: "Australia", region: "Oceania" },
  { code: "at", name: "Austria", region: "Europe" },
  { code: "az", name: "Azerbaijan", region: "Asia" },
  { code: "bs", name: "Bahamas", region: "Americas" },
  { code: "bh", name: "Bahrain", region: "Asia" },
  { code: "bd", name: "Bangladesh", region: "Asia" },
  { code: "bb", name: "Barbados", region: "Americas" },
  { code: "by", name: "Belarus", region: "Europe" },
  { code: "be", name: "Belgium", region: "Europe" },
  { code: "bz", name: "Belize", region: "Americas" },
  { code: "bj", name: "Benin", region: "Africa" },
  { code: "bt", name: "Bhutan", region: "Asia" },
  { code: "bo", name: "Bolivia", region: "Americas" },
  { code: "ba", name: "Bosnia and Herzegovina", region: "Europe" },
  { code: "bw", name: "Botswana", region: "Africa" },
  { code: "br", name: "Brazil", region: "Americas" },
  { code: "bn", name: "Brunei", region: "Asia" },
  { code: "bg", name: "Bulgaria", region: "Europe" },
  { code: "bf", name: "Burkina Faso", region: "Africa" },
  { code: "bi", name: "Burundi", region: "Africa" },
  { code: "cv", name: "Cabo Verde", region: "Africa" },
  { code: "kh", name: "Cambodia", region: "Asia" },
  { code: "cm", name: "Cameroon", region: "Africa" },
  { code: "ca", name: "Canada", region: "Americas" },
  { code: "cf", name: "Central African Republic", region: "Africa" },
  { code: "td", name: "Chad", region: "Africa" },
  { code: "cl", name: "Chile", region: "Americas" },
  { code: "cn", name: "China", region: "Asia" },
  { code: "co", name: "Colombia", region: "Americas" },
  { code: "km", name: "Comoros", region: "Africa" },
  { code: "cg", name: "Congo", region: "Africa" },
  { code: "cd", name: "Congo (DR)", region: "Africa" },
  { code: "cr", name: "Costa Rica", region: "Americas" },
  { code: "ci", name: "Cote d'Ivoire", region: "Africa" },
  { code: "hr", name: "Croatia", region: "Europe" },
  { code: "cu", name: "Cuba", region: "Americas" },
  { code: "cy", name: "Cyprus", region: "Europe" },
  { code: "cz", name: "Czechia", region: "Europe" },
  { code: "dk", name: "Denmark", region: "Europe" },
  { code: "dj", name: "Djibouti", region: "Africa" },
  { code: "dm", name: "Dominica", region: "Americas" },
  { code: "do", name: "Dominican Republic", region: "Americas" },
  { code: "ec", name: "Ecuador", region: "Americas" },
  { code: "eg", name: "Egypt", region: "Africa" },
  { code: "sv", name: "El Salvador", region: "Americas" },
  { code: "gq", name: "Equatorial Guinea", region: "Africa" },
  { code: "er", name: "Eritrea", region: "Africa" },
  { code: "ee", name: "Estonia", region: "Europe" },
  { code: "sz", name: "Eswatini", region: "Africa" },
  { code: "et", name: "Ethiopia", region: "Africa" },
  { code: "fj", name: "Fiji", region: "Oceania" },
  { code: "fi", name: "Finland", region: "Europe" },
  { code: "fr", name: "France", region: "Europe" },
  { code: "ga", name: "Gabon", region: "Africa" },
  { code: "gm", name: "Gambia", region: "Africa" },
  { code: "ge", name: "Georgia", region: "Asia" },
  { code: "de", name: "Germany", region: "Europe" },
  { code: "gh", name: "Ghana", region: "Africa" },
  { code: "gr", name: "Greece", region: "Europe" },
  { code: "gd", name: "Grenada", region: "Americas" },
  { code: "gt", name: "Guatemala", region: "Americas" },
  { code: "gn", name: "Guinea", region: "Africa" },
  { code: "gw", name: "Guinea-Bissau", region: "Africa" },
  { code: "gy", name: "Guyana", region: "Americas" },
  { code: "ht", name: "Haiti", region: "Americas" },
  { code: "va", name: "Vatican City", region: "Europe" },
  { code: "hn", name: "Honduras", region: "Americas" },
  { code: "hu", name: "Hungary", region: "Europe" },
  { code: "is", name: "Iceland", region: "Europe" },
  { code: "in", name: "India", region: "Asia" },
  { code: "id", name: "Indonesia", region: "Asia" },
  { code: "ir", name: "Iran", region: "Asia" },
  { code: "iq", name: "Iraq", region: "Asia" },
  { code: "ie", name: "Ireland", region: "Europe" },
  { code: "il", name: "Israel", region: "Asia" },
  { code: "it", name: "Italy", region: "Europe" },
  { code: "jm", name: "Jamaica", region: "Americas" },
  { code: "jp", name: "Japan", region: "Asia" },
  { code: "jo", name: "Jordan", region: "Asia" },
  { code: "kz", name: "Kazakhstan", region: "Asia" },
  { code: "ke", name: "Kenya", region: "Africa" },
  { code: "ki", name: "Kiribati", region: "Oceania" },
  { code: "kp", name: "North Korea", region: "Asia" },
  { code: "kr", name: "South Korea", region: "Asia" },
  { code: "kw", name: "Kuwait", region: "Asia" },
  { code: "kg", name: "Kyrgyzstan", region: "Asia" },
  { code: "la", name: "Laos", region: "Asia" },
  { code: "lv", name: "Latvia", region: "Europe" },
  { code: "lb", name: "Lebanon", region: "Asia" },
  { code: "ls", name: "Lesotho", region: "Africa" },
  { code: "lr", name: "Liberia", region: "Africa" },
  { code: "ly", name: "Libya", region: "Africa" },
  { code: "li", name: "Liechtenstein", region: "Europe" },
  { code: "lt", name: "Lithuania", region: "Europe" },
  { code: "lu", name: "Luxembourg", region: "Europe" },
  { code: "mg", name: "Madagascar", region: "Africa" },
  { code: "mw", name: "Malawi", region: "Africa" },
  { code: "my", name: "Malaysia", region: "Asia" },
  { code: "mv", name: "Maldives", region: "Asia" },
  { code: "ml", name: "Mali", region: "Africa" },
  { code: "mt", name: "Malta", region: "Europe" },
  { code: "mh", name: "Marshall Islands", region: "Oceania" },
  { code: "mr", name: "Mauritania", region: "Africa" },
  { code: "mu", name: "Mauritius", region: "Africa" },
  { code: "mx", name: "Mexico", region: "Americas" },
  { code: "fm", name: "Micronesia", region: "Oceania" },
  { code: "md", name: "Moldova", region: "Europe" },
  { code: "mc", name: "Monaco", region: "Europe" },
  { code: "mn", name: "Mongolia", region: "Asia" },
  { code: "me", name: "Montenegro", region: "Europe" },
  { code: "ma", name: "Morocco", region: "Africa" },
  { code: "mz", name: "Mozambique", region: "Africa" },
  { code: "mm", name: "Myanmar", region: "Asia" },
  { code: "na", name: "Namibia", region: "Africa" },
  { code: "nr", name: "Nauru", region: "Oceania" },
  { code: "np", name: "Nepal", region: "Asia" },
  { code: "nl", name: "Netherlands", region: "Europe" },
  { code: "nz", name: "New Zealand", region: "Oceania" },
  { code: "ni", name: "Nicaragua", region: "Americas" },
  { code: "ne", name: "Niger", region: "Africa" },
  { code: "ng", name: "Nigeria", region: "Africa" },
  { code: "mk", name: "North Macedonia", region: "Europe" },
  { code: "no", name: "Norway", region: "Europe" },
  { code: "om", name: "Oman", region: "Asia" },
  { code: "pk", name: "Pakistan", region: "Asia" },
  { code: "pw", name: "Palau", region: "Oceania" },
  { code: "pa", name: "Panama", region: "Americas" },
  { code: "pg", name: "Papua New Guinea", region: "Oceania" },
  { code: "py", name: "Paraguay", region: "Americas" },
  { code: "pe", name: "Peru", region: "Americas" },
  { code: "ph", name: "Philippines", region: "Asia" },
  { code: "pl", name: "Poland", region: "Europe" },
  { code: "pt", name: "Portugal", region: "Europe" },
  { code: "qa", name: "Qatar", region: "Asia" },
  { code: "ro", name: "Romania", region: "Europe" },
  { code: "ru", name: "Russia", region: "Europe" },
  { code: "rw", name: "Rwanda", region: "Africa" },
  { code: "kn", name: "Saint Kitts and Nevis", region: "Americas" },
  { code: "lc", name: "Saint Lucia", region: "Americas" },
  { code: "vc", name: "Saint Vincent and the Grenadines", region: "Americas" },
  { code: "ws", name: "Samoa", region: "Oceania" },
  { code: "sm", name: "San Marino", region: "Europe" },
  { code: "st", name: "Sao Tome and Principe", region: "Africa" },
  { code: "sa", name: "Saudi Arabia", region: "Asia" },
  { code: "sn", name: "Senegal", region: "Africa" },
  { code: "rs", name: "Serbia", region: "Europe" },
  { code: "sc", name: "Seychelles", region: "Africa" },
  { code: "sl", name: "Sierra Leone", region: "Africa" },
  { code: "sg", name: "Singapore", region: "Asia" },
  { code: "sk", name: "Slovakia", region: "Europe" },
  { code: "si", name: "Slovenia", region: "Europe" },
  { code: "sb", name: "Solomon Islands", region: "Oceania" },
  { code: "so", name: "Somalia", region: "Africa" },
  { code: "za", name: "South Africa", region: "Africa" },
  { code: "ss", name: "South Sudan", region: "Africa" },
  { code: "es", name: "Spain", region: "Europe" },
  { code: "lk", name: "Sri Lanka", region: "Asia" },
  { code: "sd", name: "Sudan", region: "Africa" },
  { code: "sr", name: "Suriname", region: "Americas" },
  { code: "se", name: "Sweden", region: "Europe" },
  { code: "ch", name: "Switzerland", region: "Europe" },
  { code: "sy", name: "Syria", region: "Asia" },
  { code: "tj", name: "Tajikistan", region: "Asia" },
  { code: "tz", name: "Tanzania", region: "Africa" },
  { code: "th", name: "Thailand", region: "Asia" },
  { code: "tl", name: "Timor-Leste", region: "Asia" },
  { code: "tg", name: "Togo", region: "Africa" },
  { code: "to", name: "Tonga", region: "Oceania" },
  { code: "tt", name: "Trinidad and Tobago", region: "Americas" },
  { code: "tn", name: "Tunisia", region: "Africa" },
  { code: "tr", name: "Turkey", region: "Asia" },
  { code: "tm", name: "Turkmenistan", region: "Asia" },
  { code: "tv", name: "Tuvalu", region: "Oceania" },
  { code: "ug", name: "Uganda", region: "Africa" },
  { code: "ua", name: "Ukraine", region: "Europe" },
  { code: "ae", name: "United Arab Emirates", region: "Asia" },
  { code: "gb", name: "United Kingdom", region: "Europe" },
  { code: "us", name: "United States", region: "Americas" },
  { code: "uy", name: "Uruguay", region: "Americas" },
  { code: "uz", name: "Uzbekistan", region: "Asia" },
  { code: "vu", name: "Vanuatu", region: "Oceania" },
  { code: "ve", name: "Venezuela", region: "Americas" },
  { code: "vn", name: "Vietnam", region: "Asia" },
  { code: "ye", name: "Yemen", region: "Asia" },
  { code: "zm", name: "Zambia", region: "Africa" },
  { code: "zw", name: "Zimbabwe", region: "Africa" },
];

export const flagUrl = (code: string): string => `/flags/${code}.svg`;

export const findCountry = (code: string): Country | undefined =>
  COUNTRIES.find((c) => c.code === code);

/** Case-insensitive name/region search. Empty query returns all. */
export const searchCountries = (query: string): Country[] => {
  const q = query.trim().toLowerCase();
  if (!q) return COUNTRIES;
  return COUNTRIES.filter(
    (c) =>
      c.name.toLowerCase().includes(q) || c.region.toLowerCase().includes(q),
  );
};
